name: dhikr_app
description: "A simple morning and evening Dhikr App."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.3+6

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  country_icons: ^3.0.0
  url_launcher: ^6.3.0
  package_info_plus: ^8.3.0
  google_mobile_ads: ^6.0.0
  device_info_plus: ^11.3.3
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.0
  permission_handler: ^12.0.0+1
  intl: ^0.20.2
  in_app_update: ^4.2.3
  screenshot: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  package_rename: ^1.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/dhikr/morning/dhikr_morning_id.json
    - assets/dhikr/evening/dhikr_evening_id.json
    - assets/dhikr/morning/dhikr_morning_en.json
    - assets/dhikr/evening/dhikr_evening_en.json
    - assets/lang/en.json
    - assets/lang/id.json
    - assets/logo/dhikr-app-logo.png
    - assets/logo/dhikr-app-logo-foreground.png
    - assets/icons/icons8/evening-office-l/icons8-evening-50.png
    - assets/icons/icons8/morning-office-l/icons8-morning-80.png
    - assets/icons/icons8/morning-office-l/icons8-morning-100.png
    - assets/icons/icons8/evening-office-l/icons8-evening-50.png
    - assets/icons/icons8/evening-office-l/icons8-evening-80.png
    - assets/icons/icons8/evening-office-l/icons8-evening-100.png

  fonts:
    - family: AmiriQuran
      fonts:
        - asset: assets/fonts/AmiriQuran-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/dhikr-app-logo.png"
  adaptive_icon_foreground: "assets/logo/dhikr-app-logo-foreground.png"
  adaptive_icon_background: "#ffffff"