name: dhikr_app
description: "A morning and evening Dhikr App."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  country_icons: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^6.0.0
  mockito: ^5.0.0
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/dhikr/morning/dhikr_morning_id.json
    - assets/dhikr/evening/dhikr_evening_id.json
    - assets/dhikr/morning/dhikr_morning_en.json
    - assets/dhikr/evening/dhikr_evening_en.json
    - assets/lang/en.json
    - assets/lang/id.json
    - assets/logo/dhikr-app-logo.png
    - assets/logo/dhikr-app-logo-foreground.png

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/AmiriQuran-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/dhikr-app-logo.png"
  adaptive_icon_foreground: "assets/logo/dhikr-app-logo-foreground.png"
  adaptive_icon_background: "#008000"